[
    {
        "name": "deleteLocal",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/deleteLocal",
        "gitUrl": "git://github.com/montymcblaster88/deleteLocal.git",
        "sshUrl": "git@github.com:montymcblaster88/deleteLocal.git",
        "default": "main",
        "targetName": "main",
        "localPath": "/Users/gareth/Code/monty/deleteLocal",
        "currentBranch": "master",
        "status": ["Delete master."],
        "hasMaster": False,
        "hasTarget": True,
        "localHasMaster": True,
        "localHasTarget": True,
        "pending": [],
        "updated": True,
    },
    {
        "name": "deleteLocalAndRemote",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/deleteLocalAndRemote",
        "gitUrl": "git://github.com/montymcblaster88/deleteLocalAndRemote.git",
        "sshUrl": "git@github.com:montymcblaster88/deleteLocalAndRemote.git",
        "default": "main",
        "targetName": "main",
        "localPath": "/Users/gareth/Code/monty/deleteLocalAndRemote",
        "currentBranch": "main",
        "status": ["Already blasted."],
        "hasMaster": False,
        "hasTarget": True,
        "localHasMaster": False,
        "localHasTarget": True,
    },
    {
        "name": "deleteRemoteClone",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/deleteRemoteClone",
        "gitUrl": "git://github.com/montymcblaster88/deleteRemoteClone.git",
        "sshUrl": "git@github.com:montymcblaster88/deleteRemoteClone.git",
        "default": "main",
        "targetName": "main",
        "localPath": "/Users/gareth/Code/monty/master-blaster-montymcblaster88/montymcblaster88/deleteRemoteClone",
        "currentBranch": "main",
        "status": ["Already blasted."],
        "hasMaster": False,
        "hasTarget": True,
        "localHasMaster": False,
        "localHasTarget": True,
    },
    {
        "name": "deleteRemoteLocal",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/deleteRemoteLocal",
        "gitUrl": "git://github.com/montymcblaster88/deleteRemoteLocal.git",
        "sshUrl": "git@github.com:montymcblaster88/deleteRemoteLocal.git",
        "default": "main",
        "targetName": "main",
        "localPath": "/Users/gareth/Code/monty/deleteRemoteLocal",
        "currentBranch": "main",
        "status": ["Path unclear."],
        "hasTarget": True,
        "hasMaster": True,
        "localHasMaster": False,
        "localHasTarget": True,
    },
    {
        "name": "localUpdateProcess",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/localUpdateProcess",
        "gitUrl": "git://github.com/montymcblaster88/localUpdateProcess.git",
        "sshUrl": "git@github.com:montymcblaster88/localUpdateProcess.git",
        "default": "master",
        "targetName": "main",
        "localPath": "/Users/gareth/Code/monty/localUpdateProcess",
        "currentBranch": "master",
        "status": ["Path unclear."],
        "hasTarget": True,
        "hasMaster": True,
        "localHasMaster": True,
        "localHasTarget": False,
    },
    {
        "name": "mvThirdToTargetAndBlastLocalMaster",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/mvThirdToTargetAndBlastLocalMaster",
        "gitUrl": "git://github.com/montymcblaster88/mvThirdToTargetAndBlastLocalMaster.git",
        "sshUrl": "git@github.com:montymcblaster88/mvThirdToTargetAndBlastLocalMaster.git",
        "default": "main",
        "targetName": "main",
        "localPath": "/Users/gareth/Code/monty/mvThirdToTargetAndBlastLocalMaster",
        "currentBranch": "main",
        "status": ["Already blasted."],
        "hasMaster": False,
        "hasTarget": True,
        "localHasMaster": False,
        "localHasTarget": True,
    },
    {
        "name": "mvThirdToTargetAndBlastRemoteAndLocal",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/mvThirdToTargetAndBlastRemoteAndLocal",
        "gitUrl": "git://github.com/montymcblaster88/mvThirdToTargetAndBlastRemoteAndLocal.git",
        "sshUrl": "git@github.com:montymcblaster88/mvThirdToTargetAndBlastRemoteAndLocal.git",
        "default": "main",
        "targetName": "main",
        "localPath": "/Users/gareth/Code/monty/mvThirdToTargetAndBlastRemoteAndLocal",
        "currentBranch": "master",
        "status": ["Delete master."],
        "hasTarget": True,
        "hasMaster": True,
        "localHasMaster": True,
        "localHasTarget": False,
        "pending": [],
        "updated": True,
    },
    {
        "name": "mvThirdToTargetAndBlastRemoteMasterClone",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/mvThirdToTargetAndBlastRemoteMasterClone",
        "gitUrl": "git://github.com/montymcblaster88/mvThirdToTargetAndBlastRemoteMasterClone.git",
        "sshUrl": "git@github.com:montymcblaster88/mvThirdToTargetAndBlastRemoteMasterClone.git",
        "default": "prod",
        "targetName": "main",
        "hasTarget": False,
        "hasMaster": True,
        "status": ["Path unclear."],
    },
    {
        "name": "mvThirdToTargetAndBlastRemoteMasterLocal",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/mvThirdToTargetAndBlastRemoteMasterLocal",
        "gitUrl": "git://github.com/montymcblaster88/mvThirdToTargetAndBlastRemoteMasterLocal.git",
        "sshUrl": "git@github.com:montymcblaster88/mvThirdToTargetAndBlastRemoteMasterLocal.git",
        "default": "prod",
        "targetName": "main",
        "localPath": "/Users/gareth/Code/monty/mvThirdToTargetAndBlastRemoteMasterLocal",
        "currentBranch": "prod",
        "status": ["Path unclear."],
        "hasTarget": False,
        "hasMaster": True,
        "localHasMaster": False,
        "localHasTarget": False,
    },
    {
        "name": "mvThirdToTargetClone",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/mvThirdToTargetClone",
        "gitUrl": "git://github.com/montymcblaster88/mvThirdToTargetClone.git",
        "sshUrl": "git@github.com:montymcblaster88/mvThirdToTargetClone.git",
        "default": "main",
        "targetName": "main",
        "hasMaster": False,
        "hasTarget": True,
        "status": ["Already blasted."],
    },
    {
        "name": "mvThirdToTargetLocal",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/mvThirdToTargetLocal",
        "gitUrl": "git://github.com/montymcblaster88/mvThirdToTargetLocal.git",
        "sshUrl": "git@github.com:montymcblaster88/mvThirdToTargetLocal.git",
        "default": "main",
        "targetName": "main",
        "localPath": "/Users/gareth/Code/monty/mvThirdToTargetLocal",
        "currentBranch": "prod",
        "status": ["Path unclear."],
        "hasMaster": False,
        "hasTarget": True,
        "localHasMaster": False,
        "localHasTarget": False,
    },
    {
        "name": "myPrivateRepo",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/myPrivateRepo",
        "gitUrl": "git://github.com/montymcblaster88/myPrivateRepo.git",
        "sshUrl": "git@github.com:montymcblaster88/myPrivateRepo.git",
        "default": "master",
        "targetName": "main",
        "hasTarget": True,
        "hasMaster": True,
        "status": ["Path unclear."],
    },
    {
        "name": "remoteProcessClone",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/remoteProcessClone",
        "gitUrl": "git://github.com/montymcblaster88/remoteProcessClone.git",
        "sshUrl": "git@github.com:montymcblaster88/remoteProcessClone.git",
        "default": "main",
        "targetName": "main",
        "hasMaster": False,
        "hasTarget": True,
        "status": ["Already blasted."],
    },
    {
        "name": "remoteProcessLocal",
        "ownerLogin": "montymcblaster88",
        "htmlUrl": "https://github.com/montymcblaster88/remoteProcessLocal",
        "gitUrl": "git://github.com/montymcblaster88/remoteProcessLocal.git",
        "sshUrl": "git@github.com:montymcblaster88/remoteProcessLocal.git",
        "default": "main",
        "targetName": "main",
        "localPath": "/Users/gareth/Code/monty/remoteProcessLocal",
        "currentBranch": "master",
        "status": ["Delete master."],
        "hasTarget": True,
        "hasMaster": True,
        "localHasMaster": True,
        "localHasTarget": False,
        "pending": [],
        "updated": True,
    },
]
