repos = [
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/accountNumber',
        'name': 'accountNumber', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/beginner-javascript',
     'name': 'beginner-javascript', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'master', 'htmlUrl': 'https://github.com/Twitchkidd/blastIt',
     'name': 'blastIt', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/bookBoxSort',
     'name': 'bookBoxSort', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/borg-david',
     'name': 'borg-david', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/CheeryTomato',
     'name': 'CheeryTomato', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/code-etc',
     'name': 'code-etc', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/dang-thats-delicious',
     'name': 'dang-thats-delicious', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'prod', 'htmlUrl': 'https://github.com/Twitchkidd/defaultNotMasterConflict',
     'name': 'defaultNotMasterConflict', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/dep-gfcom',
     'name': 'dep-gfcom', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/dep-run-club-web',
     'name': 'dep-run-club-web', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/dep-server',
     'name': 'dep-server', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/dots',
     'name': 'dots', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/EggheadToDoApp',
     'name': 'EggheadToDoApp', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/Enzyme-React-Native-32',
     'name': 'Enzyme-React-Native-32', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'master', 'htmlUrl': 'https://github.com/Twitchkidd/externalMainConflict',
     'name': 'externalMainConflict', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/fonts',
     'name': 'fonts', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/forms',
     'name': 'forms', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/GarethDotCom',
     'name': 'GarethDotCom', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/gfcom',
     'name': 'gfcom', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/gfcom-blog',
     'name': 'gfcom-blog', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/gfcom-public-html',
     'name': 'gfcom-public-html', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/intro-mb',
     'name': 'intro-mb', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/intro-mb-htmlcss',
     'name': 'intro-mb-htmlcss', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/intro-mb-javascript',
     'name': 'intro-mb-javascript', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/intro-mb-python',
     'name': 'intro-mb-python', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/jetifier',
     'name': 'jetifier', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/laa',
     'name': 'laa', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/learn-node',
     'name': 'learn-node', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/level-up-react-2',
     'name': 'level-up-react-2', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'master', 'htmlUrl': 'https://github.com/Twitchkidd/locallyBlastIt',
     'name': 'locallyBlastIt', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/localMasterDelete',
     'name': 'localMasterDelete', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/Logoed',
     'name': 'Logoed', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/logoed-server',
     'name': 'logoed-server', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/logoed-web-app',
     'name': 'logoed-web-app', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/master-blaster',
     'name': 'master-blaster', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/moodbit',
     'name': 'moodbit', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/Moving-Circle',
     'name': 'Moving-Circle', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/MultiBounce',
     'name': 'MultiBounce', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/NaderDabitNavigatorExperimentalCodeAlong',
     'name': 'NaderDabitNavigatorExperimentalCodeAlong', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/phpTest',
     'name': 'phpTest', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/polar-pairs',
     'name': 'polar-pairs', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/pom',
     'name': 'pom', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/ReactNativeTemplate',
     'name': 'ReactNativeTemplate', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/ReactNavigationReduxTest',
     'name': 'ReactNavigationReduxTest', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/recurring',
     'name': 'recurring', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/RNWebviewMicPermission',
     'name': 'RNWebviewMicPermission', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/rocktober',
     'name': 'rocktober', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/Roll-a-Ball',
     'name': 'Roll-a-Ball', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/RR-TodoList',
     'name': 'RR-TodoList', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/run-club-server',
     'name': 'run-club-server', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/run-club-web',
     'name': 'run-club-web', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/RunClub',
     'name': 'RunClub', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/server',
     'name': 'server', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/shellScripts',
     'name': 'shellScripts', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/site-deets',
     'name': 'site-deets', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/slider-app',
     'name': 'slider-app', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/spukee-site-react',
     'name': 'spukee-site-react', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/sqrrlSite',
     'name': 'sqrrlSite', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/tc-net',
     'name': 'tc-net', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/tech-test-react-wordcloud',
     'name': 'tech-test-react-wordcloud', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/tefTest',
     'name': 'tefTest', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/test',
     'name': 'test', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/test-cra',
     'name': 'test-cra', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/test-html',
     'name': 'test-html', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/testMe',
     'name': 'testMe', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/testTest',
     'name': 'testTest', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/TrailCity',
     'name': 'TrailCity', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/web-dev-reboot',
     'name': 'web-dev-reboot', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'master', 'htmlUrl': 'https://github.com/Twitchkidd/who',
     'name': 'who', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/Who2Heal',
     'name': 'Who2Heal', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/whole-code-folder',
     'name': 'whole-code-folder', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/whole-logoed-folder',
     'name': 'whole-logoed-folder', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/wild-rydes-react-native-no-mfa',
     'name': 'wild-rydes-react-native-no-mfa', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/windowsTest',
     'name': 'windowsTest', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'},
    {'defaultBranch': 'main', 'htmlUrl': 'https://github.com/Twitchkidd/yusuff-faruq-context-demo', 'name': 'yusuff-faruq-context-demo', 'owner-login': 'Twitchkidd', 'primaryBranchName': 'main'}]
